name: Fl_semol
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - charset-normalizer=3.4.4
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - greenlet=3.3.0
  - icu=75.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.11.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libnsl=2.0.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libpq=18.1
  - librdkit=2025.09.4
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.44
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycairo=1.29.0
  - pyparsing=3.3.1
  - python=3.10.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - rdkit=2025.09.4
  - readline=8.3
  - reportlab=4.4.7
  - rlpycairo=0.4.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=2.0.45
  - sqlite=3.51.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - littleutils==0.2.4
      - markupsafe==2.1.5
      - mock==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ogb==1.3.6
      - outdated==0.2.2
      - pillow==12.0.0
      - propcache==0.4.1
      - psutil==7.2.1
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - subword-nmt==0.3.8
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.5.1+cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.1.0
      - urllib3==2.6.2
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /root/miniconda3/envs/Fl_semol
